class SessionError(Exception): ...

class SessionCompleted(SessionError): ...
class SessionExpired(SessionError): ...

class UnknownParticipant(SessionError): ...
class TooManyParticipants(SessionError): ...
class ParticipantAlreadyAnswered(SessionError): ...
